version: '3'

services:
  socialstuff_identity_web_dev:
    container_name: socialstuff_identity_web_dev
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - socialstuff_identity_network_dev
    depends_on:
      - socialstuff_identity_mysql_dev
    volumes:
    - ../..:/app
    environment:
      MYSQL_DATABASE: socialstuff_identity_dev
      MYSQL_HOST: socialstuff_identity_mysql_dev

  socialstuff_identity_mysql_dev:
    container_name: socialstuff_identity_mysql_dev
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socialstuff_identity_dev
    networks:
      - socialstuff_identity_network_dev

networks:
  socialstuff_identity_network_dev:
