version: '3'

services:
  socialstuff_chat_web_dev:
    container_name: socialstuff_chat_web_dev
    hostname: socialstuff_chat_web_dev
    build:
      context: services/chat
      dockerfile: docker/dev/Dockerfile
    networks:
      - socialstuff_chat_network_dev
      - socialstuff_network_dev
    depends_on:
      - socialstuff_identity_web_dev
      - socialstuff_chat_mongo_dev
    volumes:
    - ./services/chat:/app
    environment:
      NODE_ENV: dev

  socialstuff_chat_mongo_dev:
    container_name: socialstuff_chat_mongo_dev
    hostname: socialstuff_chat_mongo_dev
    image: mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - socialstuff_chat_network_dev
    ports:
    - "27017:27017"
  
  socialstuff_identity_web_dev:
    container_name: socialstuff_identity_web_dev
    hostname: socialstuff_identity_web_dev
    build:
      context: services/identity
      dockerfile: docker/dev/Dockerfile
    networks:
      - socialstuff_identity_network_dev
      - socialstuff_network_dev
    depends_on:
      - socialstuff_identity_mysql_dev
    volumes:
    - ./services/identity:/app
    environment:
      NODE_ENV: dev

  socialstuff_identity_mysql_dev:
    container_name: socialstuff_identity_mysql_dev
    hostname: socialstuff_identity_mysql_dev
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socialstuff_identity_dev
    networks:
      - socialstuff_identity_network_dev
  
  
  socialstuff_nginx_dev:
    container_name: socialstuff_nginx_dev
    hostname: socialstuff_nginx_dev
    build:
      context: deployment/reverse_proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - socialstuff_network_dev
    environment:
      - NGINX_PORT=80

networks:
  socialstuff_network_dev:
  socialstuff_chat_network_dev:
  socialstuff_identity_network_dev:
