version: '3'

services:
  socialstuff_chat_web_dev:
    container_name: socialstuff_chat_web_dev
    hostname: socialstuff_chat_web_dev
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3100:3000"
    networks:
      - socialstuff_chat_network_dev
    depends_on:
      - socialstuff_chat_mongo_dev
    volumes:
    - ../..:/app
    environment:
      NODE_ENV: dev

  socialstuff_chat_mongo_dev:
    container_name: socialstuff_chat_mongo_dev
    hostname: socialstuff_chat_mongo_dev
    image: mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - socialstuff_chat_network_dev
    ports:
    - "27017:27017"

networks:
  socialstuff_chat_network_dev:
